package de.th.ecobobackend.model.enums;

public enum NewsfeedType {
    NONE,
    ADMIN_MESSAGE,
    ECOELEMENT_ADDED,
    ECOELEMENT_REVIEWED,
    ECOELEMENT_IN_DELETE_PROCESS,
    ECOELEMENT_DELETED,
    ECOELEMENT_UPDATED,
    USER_REGISTRATION,
}
